dbdata:
- item: DBMS Type
  type: text
  value: postgres
- item: DBMS DB Name
  type: text
  value: avistadb
- item: DBMS IP Address
  type: text
  value: localhost
- item: DBMS Port
  type: text
  value: '5432'
- item: DBMS Username
  type: text
  value: avista
- item: DBMS Password
  type: password
  value: avistapw
service:
  host: localhost
  port: '5000'
sysdata:
- item: System Identifier
  type: text
  value: df0bcb642bd44c37a06882cd13179cb0
- item: Equipment Monitored
  type: text
  value: ''
- item: Location
  type: text
  value: ''
- item: Data Collection Periodicity (ms)
  type: number
  value: 5000
- item: Server Port
  type: number
  value: 5000
